name: rnn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - pip:
    - notebook
    - opencv_python
    - --extra-index-url=https://download.pytorch.org/whl/cu118 # use GPU
    - torch>=2.0.0
    - torchvision>=0.15.0
    - torchaudio>=2.0.0